name: Train and Upload ML Model

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python src/train.py

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shelf-life-mlflow-artifacts
        path: /tmp/mlruns
